spring:
  config:
    activate:
      on-profile: prod
  server:
    port: 8080
      tomcat:
        max-http-post-size: 3221225472  # 3GB
        max-swallow-size: 3221225472    # 3GB
      
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:3306/wodify
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    tomcat:
      max-active: 5
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: true
  redis:
    host: ${REDIS_HOST}
    port: 6379
  rabbitmq:
    host: ${MQ_HOST}
    port: 5671
    username: ${MQ_USERNAME}
    password: ${MQ_PASSWORD}
    virtual-host: /
    ssl:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: wodify-image

jwt:
  expiration: 30
  secretKey: ${JWT_SECRET}
  expirationRt: 14400
  secretKeyRt: ${JWT_SECRET_RT}
